version: 2

updates:
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: monthly
    allow:
      - dependency-name: traefik
    open-pull-requests-limit: 1
    commit-message:
      prefix: build(edge)
